name: ubuntu-latest

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  clang-minimum:
    name: clang++-6
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsodium-dev libcrypto++-dev libboost-all-dev
        sudo apt-get install -y clang-6.0 lldb-6.0 lld-6.0 clang-format-6.0
    - name: cmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++-6.0
    - name: build
      run: cmake --build build -j$(nproc)
    - name: test
      run: ./build/tests/tests
    - name: examples
      run: |
        sudo make install -C build
        cd examples
        cmake -B build -DCMAKE_CXX_COMPILER=clang++-6.0
        make -C build
        ./build/create_simple_packet
        ./build/encoding_and_decoding
        ./build/key_from_raw_data

  clang-9:
    name: clang++-9
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsodium-dev libcrypto++-dev libboost-all-dev
        sudo apt-get install -y clang-9 lldb-9 lld-9 clang-format-9
    - name: cmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++-9
    - name: build
      run: cmake --build build -j$(nproc)
    - name: test
      run: ./build/tests/tests
    - name: examples
      run: |
        sudo make install -C build
        cd examples
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++-9
        make -C build
        ./build/create_simple_packet
        ./build/encoding_and_decoding
        ./build/key_from_raw_data

  clang-14:
    name: clang++-14
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsodium-dev libcrypto++-dev libboost-all-dev
    - name: cmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++-14
    - name: build
      run: cmake --build build -j$(nproc)
    - name: test
      run: ./build/tests/tests
    - name: examples
      run: |
        sudo make install -C build
        cd examples
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++-14
        make -C build
        ./build/create_simple_packet
        ./build/encoding_and_decoding
        ./build/key_from_raw_data

  gcc-minimum:
    name: g++-8
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsodium-dev libcrypto++-dev libboost-all-dev
        sudo apt-get install -y g++-8
    - name: cmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-8
    - name: build
      run: cmake --build build -j$(nproc)
    - name: test
      run: ./build/tests/tests
    - name: examples
      run: |
        sudo make install -C build
        cd examples
        cmake -B build -DCMAKE_CXX_COMPILER=g++-8
        make -C build
        ./build/create_simple_packet
        ./build/encoding_and_decoding
        ./build/key_from_raw_data

  gcc-9:
    name: g++-9
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsodium-dev libcrypto++-dev libboost-all-dev
    - name: cmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-9
    - name: build
      run: cmake --build build -j$(nproc)
    - name: test
      run: ./build/tests/tests
    - name: examples
      run: |
        sudo make install -C build
        cd examples
        cmake -B build -DCMAKE_CXX_COMPILER=g++-9
        make -C build
        ./build/create_simple_packet
        ./build/encoding_and_decoding
        ./build/key_from_raw_data

  gcc-11:
    name: g++-11
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsodium-dev libcrypto++-dev libboost-all-dev
    - name: cmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-11
    - name: build
      run: cmake --build build -j$(nproc)
    - name: test
      run: ./build/tests/tests
    - name: examples
      run: |
        sudo make install -C build
        cd examples
        cmake -B build -DCMAKE_CXX_COMPILER=g++-11
        make -C build
        ./build/create_simple_packet
        ./build/encoding_and_decoding
        ./build/key_from_raw_data
